# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "635bb746e9f569ec0189cf6a67e65506"
name = "Auto Entry"
application_url = "https://auto-entry-app-production-4dda.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,write_products"

[auth]
redirect_urls = [ "https://auto-entry-app-production-4dda.up.railway.app/api/auth" ]
